### ISSUE TITLE
improved comment support

### ISSUE THREAD

**Issue by linuxcaffe** [hpdeifel/hledger-iadd#11]
One of the great things about *ledger files is that comments are fully supported, with possible tags and any kind of metadata, as transaction, or posting comments. see http://hledger.org/journal.html#comments

I'm using iadd (nice, thanks) while I *can* add a transaction comment, immediately after the description, and wish I could add posting comments, or really, use iadd with comments wherever the format permits it.

I'd like to be able to accept the default AND add a comment, to most (all?) iadd prompts, by using a leading comment-character ( ; # or *). Following the journal format, using indentation indicates what part of the record the comments apply to, so Prompt: [whitespace]< comment-character > COMMENT should be supported as well.

**Comment by hpdeifel** [comment]
Very good idea!

@t-wissmann once suggested adding a keybinding for comments. I don't know which UI is better. Your approach requires splitting the input into pre-comment and comment parts and treating them differently for completion, etc. A keybinding would not require this but add another modal dialog to the UI.

For your suggestion it would probably be a good idea to highlight the different parts of the input differently.

**Comment by t-wissmann** [comment]
As a compromise, one could have <kbd>;</kbd> as the keybinding for this.

**Comment by linuxcaffe** [comment]
sure! a keybinding would be swell, I'm not sure how it should work, as long as one could
- add a comment to a) journal, b) transaction or c) posting
- add a comment to a default choice

however that might work :)

**Comment by linuxcaffe** [comment]
ok.. maybe not journal comments..

**Comment by hpdeifel** [comment]
I implemented this in #15. Feedback on the UI is greatly appreciated :-)

**Comment by hpdeifel** [comment]
This is now merged to master. It still lacks documentation and tests but is already useful.

The new comment dialog is now bound to <kbd>;</kbd>.

**Comment by linuxcaffe** [comment]
thanks! I'm eager to test it, will give feedback.

**Comment by linuxcaffe** [comment]
comment support vastly improved! Nice work, thanks!
