### ISSUE TITLE
Account Occurrence Frequency Should Be Used Rather Than Alphabetical Order

### ISSUE THREAD

**Issue by the-solipsist** [hpdeifel/hledger-iadd#13]
I mostly make payments either from `Assets:Cash` or `Assets:Savings:BankName`.  However, I also have `Assets:Deposits:BankName` for my term deposits.  Most of my entries contain `Assets:Savings:BankName`, and very few contain `Assets:Deposits:BankName`.  However, when I type `BankName`, the first suggestion is always `Assets:Deposits:BankName` since the list is arranged in alphabetical order.

**Comment by hpdeifel** [comment]
Thanks, good catch!
