### ISSUE TITLE
Contribute TextZipper functions to text-zipper

### ISSUE THREAD

**Issue by jtdaugherty** [hpdeifel/hledger-iadd#16]
Some if not all of the functions you wrote for doing "emacs-style" editing would be very welcome in the `text-zipper` package!

**Comment by hpdeifel** [comment]
Yes, I wanted to collect a few and test them before introducing them in a public API but it was definitely the plan to upstream them eventually. They would also be much easier to implement using the internals of text-zipper as opposed to just the exported interface.

**Comment by jtdaugherty** [comment]
Great! Speaking of the exported interface, I am definitely interested to know more about what could be exported or changed to make the implementation of your new functions easier.

**Comment by hpdeifel** [comment]
The primitives that I implemented myself (kinda hackish, using the public API) were:

 - get previous/next character: Preferably with a way to distinguish between EOL/BOL and EOF/BOF
 - do something (move or kill) in one direction until an arbitrary condition holds. This generalizes functions like goto/killToEOL

I don't know if any of those should be exported. Maybe prev/nextChar would be the most useful.

**Comment by jtdaugherty** [comment]
Great. For what it's worth, there's another patch in the works that I will be merging soon that might be of interest here:

https://github.com/jtdaugherty/text-zipper/pull/8

**Comment by jtdaugherty** [comment]
The test suite and implementation in `hledger-iadd` are now integrated into `text-zipper` and released:

http://hackage.haskell.org/package/text-zipper-0.10

**Comment by hpdeifel** [comment]
Nice, thanks.
