### ISSUE TITLE
hledger-iadd-1.1.4 test suite does not compile

### ISSUE THREAD

**Issue by peti** [hpdeifel/hledger-iadd#19]
Citing from http://hydra.nixos.org/build/47699412/nixlog/1/raw:

~~~
tests/Data/Text/Zipper/Generic/WordsSpec.hs:15:1: error:
    Ambiguous interface for ‘Data.Text.Zipper.Generic.Words’:
      it was found in multiple packages:
      text-zipper-0.10 hledger-iadd-1.1.4
~~~

**Comment by hpdeifel** [comment]
Yes, `text-zipper` now includes this module. I will remove it from `hledger-iadd` later today -- in the meantime compile it without tests or use an older text-zipper.

**Comment by hpdeifel** [comment]
Done and released. Thanks for reporting!
