### ISSUE TITLE
please add support for hledger-lib 1.4

### ISSUE THREAD

**Issue by peti** [hpdeifel/hledger-iadd#28]
We would like to update to the latest hledger version in both openSUSE and NixOS, but right now hledger-iadd is blocking that update because it won't build against hledger-lib 1.4. I suppose Stackage will have the same issue. If at all possible, I'd greatly appreciate getting an updated version that remedies this issue.

**Comment by hpdeifel** [comment]
I'm on it :-)

Will publish a new revision shortly...

**Comment by hpdeifel** [comment]
done

**Comment by peti** [comment]
Thank you!
