### ISSUE TITLE
Date seems to be affected by timezone changed

### ISSUE THREAD

**Issue by CarlosEvo** [hpdeifel/hledger-iadd#33]
I set up `hledger-iadd` in Europe. When I got back to the states, the default date seems to follow the time zone across the pond. e.g.:

```bash
$ date
Thu Aug 23 22:06:08 PDT 2018
$ hledger iadd
New Transaction:

 │

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Date (18/08/24):
```

Is there a way to fix this issue? Thank you!

**Comment by hpdeifel** [comment]
This was already fixed in master, but I  somehow forgot to make a release. Sorry about that, 1.3.6 should have the fix now.
