### ISSUE TITLE
changes for next hledger-lib release

### ISSUE THREAD

**Issue by simonmichael** [hpdeifel/hledger-iadd#38]
A heads-up: hledger-lib 1.12 will require megaparsec 7. 

Also, divideAmount/multiplyAmount/divideMixedAmount/multiplyMixedAmount's arguments will be flipped. I started to make a PR, but the megaparsec issue made it a bit too much work.

**Comment by hpdeifel** [comment]
Thanks for the heads up!

Do you have an ETA for the release? I'd like hledger-iadd to be ready by then

**Comment by simonmichael** [comment]
Or, it might be much sooner, https://groups.google.com/d/msg/hledger/tj16HVv8Dbs/Uw7TjwMIBwAJ

**Comment by hpdeifel** [comment]
There is now a `develop` branch that is fully ported to the current git HEAD of hledger-lib, so theoretically I could just merge and release any time
