### ISSUE TITLE
Error installing version 1.13.12

### ISSUE THREAD

**Issue by edkedk99** [hpdeifel/hledger-iadd#55]
I am trying to update my hledger-iadd folowing README instruction with the following command `stack install --resolver=lts hledger-iadd-1.3.14`
 
I get the following error:

```
hledger-iadd>     |
hledger-iadd> 102 | context _ _ dateFormat entryText (DateQuestion _) = parseDateWithToday dateFormat entryText >>= \case
hledger-iadd>     |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
hledger-iadd> 

--  While building package hledger-iadd-1.3.14 (scroll up to its section to see the error) using:
      /home/eduardok/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I understand nothing about *stack* or *haskell* but it seems to me there may be an error in the code. Is it so or it is a problem in my computer?

I have already installed version 1.3.12. I couldn't install also version 1.3.13, but I have had success installing version 1.3.12 again.

I am running Ubuntu 20.10 and I successfully installed hledger version 1.21.

The reason I want to update is because my current hledger-iadd installation doesn't accept `tag: Cash` on an account directive while hledger does accept, giving me the error below that may be fixed in the newer version:

```
invalid account type code Cash, should be one of A, L, E, R, X, ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE
```

**Comment by hpdeifel** [comment]
Hi,

This issue has unfortunately fallen through the cracks, I'm very sorry. Can you still reproduce this problem? Unfortunately I cannot reproduce it myself with stack 2.3.3. It just works on my end.

**Comment by edkedk99** [comment]
Hello,

Now I could install this version with success. I have tried to install 1.13, 1.14 and 1.15, but it returns an error. Anyway, my issue is solved.  Thank you very much for your help and for this amazing app.

**Comment by simonmichael** [comment]
Since I'm here / asking for my own interest: could you paste the full command you are running and full output ?

**Comment by simonmichael** [comment]
For hledger-iadd-1.3.15 specifically, the install command currently needs to be eg `stack install --resolver=nightly hledger-iadd-1.3.15`, because it depends on hledger 1.22 which is not yet in a stackage LTS snapshot.

**Comment by edkedk99** [comment]
Probably that was the problem. I was trying with lts
