### ISSUE TITLE
Update to brick >= 0.72

### ISSUE THREAD

**Issue by hpdeifel** [hpdeifel/hledger-iadd#71]
Currently `iadd` doesn't build with newer versions of brick. While we're at it, we might just go to brick >= 1.0

**Comment by simonmichael** [comment]
Yes please... this is causing trouble for folks wanting to install hledger-iadd with current hledger. I just noticed that hledger-install fails to install hledger-iadd at the moment.

**Comment by dotlambda** [comment]
This also breaks hledger-iadd in Nixpkgs since https://github.com/NixOS/nixpkgs/pull/202022.

**Comment by hpdeifel** [comment]
Sorry for the long delay, I finally got around to this. I'll leave it hanging before a release for a few more days, as there were quite significant changes throughout the application that I want to give some testing beforehand

**Comment by hpdeifel** [comment]
Fyi, this is now released
