### ISSUE TITLE
Update for hledger 1.32

### ISSUE THREAD

**Issue by alerque** [hpdeifel/hledger-iadd#79]
This restriction is blocking Arch Linux from updating `hledger`.

Is there any reason it can't be relaxed?

https://github.com/hpdeifel/hledger-iadd/blob/11501dd102de0ecff88e60608ef0d92fb8c6c31b/hledger-iadd.cabal#L63C53-L63C53

**Comment by hpdeifel** [comment]
As far as I can see, the API differences just affect the testsuite. Did you encounter any issues with building the main binary?  (I'm gonna make a new release regardless. Just curious)

**Comment by alerque** [comment]
I had not dug that deep, but if that's the case I'm going to build it now. We completely broke the Arch Linux package for this with an unfortunate Haskell snafu in our staging repository. If skipping tests for now is what it takes to get a working package again I'm all for it. Trying now.

**Comment by alerque** [comment]
That does appear to have worked. The Arch Linux package is unbroken now so thanks for the tip. Of course a release that doesn't need a monkey patch to change the version bounds would be good too, but…

**Comment by hpdeifel** [comment]
This took longer than it should have, but the release is now out of the door
