### ISSUE TITLE
More emacs-style keybindings in edit widget

### ISSUE THREAD

**Issue by hpdeifel** [hpdeifel/hledger-iadd#8]
Some bindings that would be nice to have:

 - <kbd>C-b</kbd>: Move one char backwards
 - <kbd>C-f</kbd>: Move one char forward
 - <kbd>M-b</kbd>: Move one word backwards
 - <kbd>M-f</kbd>: Move one word forward
 - <kbd>M-DEL</kbd>: Delete previous word
 - <kbd>M-d</kbd>: Delete next word

**Comment by t-wissmann** [comment]
- <kbd>C-w</kbd>: Delete previous word
- <kbd>C-u</kbd>: Delete to BOL (instead of: Delete entire input)

Not an emacs-binding, but readline:
- <kbd>C-d</kbd> (in the Date-Input-Box): quit

**Comment by hpdeifel** [comment]
Thanks!

> C-u: Delete to BOL (instead of: Delete entire input)

True. I already implemented this for [brick](https://github.com/jtdaugherty/brick/commit/e6dc695932e88f4257eac752c81cc4a2fb03cb65) but forgot to remove the workaround binding in `hledger-iadd`.
 
> C-d (in the Date-Input-Box): quit

That's already implemented since yesterday 😄. It now does the same as <kbd>C-c</kbd> everywhere: Directly quit in date prompt and ask in all others.
