### ISSUE TITLE
Needs an upper bound bump for hledger-lib-1.40

### ISSUE THREAD

**Issue by simonmichael** [hpdeifel/hledger-iadd#82]
A revision allowing `hledger-lib >=1.33 && <1.41` would be enough (I tested with --allow-newer).

**Comment by simonmichael** [comment]
Ping @hpdeifel

**Comment by simonmichael** [comment]
PS I'm happy to help with such revisions if you'd like me to; I'd need access at https://hackage.haskell.org/package/hledger-iadd

**Comment by hpdeifel** [comment]
Fixed, sorry for the delay!

@simonmichael I've added you as maintainer on hackage. Please feel free to publish revisions if I don't respond within a few days.
